### ISSUE TITLE
github is for FREE releases 

### ISSUE THREAD

**Issue by markbucko12341** [suryabhaiin/qbcore-admin-panel#1]
Dont use github to advertise your paid scripts.. Github is a platform for people to post there free scripts

**Comment by suryabhaiin** [comment]
ohh.. ok.. thank you for information..

**Comment by suryabhaiin** [comment]
can i report any script thais paid but its link available on github.

**Comment by markbucko12341** [comment]
what do you mean  ?

**Comment by markbucko12341** [comment]
if you have a script for sale please use the fivem forums page to advertise not github as this is for FREE releases

**Comment by suryabhaiin** [comment]
ok
